import { schema, table, t, type Infer } from 'spacetimedb/server';
import { addDeliveryNoteItemImpl, addGrnItemImpl, addLineItemImpl, advanceDeliveryNoteImpl, advanceGrnImpl, advancePipelineImpl, convertPipelineToOrderImpl, createDeliveryNoteImpl, createGrnImpl, issueDocNumber, manageOrderImpl, managePurchaseOrderImpl, recordMoneyEventImpl, resolveAiActionImpl, upsertContactImpl, upsertPartyImpl } from './milestone1_logic';
import { bootstrapAdminImpl, ensureEmail, findAccessKey, hasAnyMembers, issueAccessKeyImpl, normalizeEmail, redeemAccessKeyImpl, revokeAuthSessionImpl, upsertAuthSessionImpl } from './auth_logic';
import { saveChatMessageImpl, saveAiMemoryImpl, deleteAiMemoryImpl } from './memory_logic';

const entityStatusEnum = t.enum('EntityStatus', { Draft: t.unit(), Active: t.unit(), InProgress: t.unit(), Terminal: t.unit(), Cancelled: t.unit() });
type EntityStatus = Infer<typeof entityStatusEnum>;
const customerGradeEnum = t.enum('CustomerGrade', { A: t.unit(), B: t.unit(), C: t.unit(), D: t.unit() });
type CustomerGrade = Infer<typeof customerGradeEnum>;
const userRoleEnum = t.enum('UserRole', { Admin: t.unit(), Manager: t.unit(), Sales: t.unit(), Operations: t.unit(), Accountant: t.unit() });
type UserRole = Infer<typeof userRoleEnum>;
const authMethodEnum = t.enum('AuthMethod', { Bootstrap: t.unit(), InviteKey: t.unit() });
type AuthMethod = Infer<typeof authMethodEnum>;
const aiActionStatusEnum = t.enum('AiActionStatus', { Proposed: t.unit(), Approved: t.unit(), Executed: t.unit(), Rejected: t.unit(), Failed: t.unit() });
type AiActionStatus = Infer<typeof aiActionStatusEnum>;
const moneyEventKindEnum = t.enum('MoneyEventKind', { CustomerInvoice: t.unit(), CustomerPayment: t.unit(), SupplierInvoice: t.unit(), SupplierPayment: t.unit() });
type MoneyEventKind = Infer<typeof moneyEventKindEnum>;
const bankMatchStatusEnum = t.enum('BankMatchStatus', { Unmatched: t.unit(), Matched: t.unit(), Disputed: t.unit() });
type BankMatchStatus = Infer<typeof bankMatchStatusEnum>;
const deliveryStatusEnum = t.enum('DeliveryStatus', { Draft: t.unit(), Dispatched: t.unit(), Delivered: t.unit(), Returned: t.unit() });
const grnStatusEnum = t.enum('GRNStatus', { Draft: t.unit(), Inspecting: t.unit(), Accepted: t.unit(), Rejected: t.unit() });

const memberRow = { identity: t.identity().primaryKey(), nickname: t.string(), fullName: t.string(), email: t.string(), role: userRoleEnum, authMethod: authMethodEnum, accessKeyId: t.u64().optional(), joinedAt: t.timestamp(), lastLoginAt: t.timestamp(), updatedAt: t.timestamp() };
const partyRow = { id: t.u64().primaryKey().autoInc(), name: t.string(), code: t.string(), category: t.string(), isCustomer: t.bool(), isSupplier: t.bool(), grade: customerGradeEnum, creditLimitFils: t.u64(), isCreditBlocked: t.bool(), paymentTermsDays: t.u64(), productTypes: t.string(), annualGoalFils: t.u64(), city: t.string(), country: t.string(), phone: t.string(), email: t.string(), source: t.string(), active2024: t.bool(), active2025: t.bool(), active2026: t.bool(), notes: t.string(), bankIban: t.string(), bankSwift: t.string(), bankAccountName: t.string(), createdAt: t.timestamp(), updatedAt: t.timestamp() };
const contactRow = { id: t.u64().primaryKey().autoInc(), partyId: t.u64(), name: t.string(), designation: t.string(), phone: t.string(), email: t.string(), isWhatsApp: t.bool() };
const accessKeyRow = { id: t.u64().primaryKey().autoInc(), key: t.string(), role: userRoleEnum, assignedEmail: t.string(), assignedName: t.string(), notes: t.string(), createdBy: t.identity(), createdAt: t.timestamp(), expiresAt: t.timestamp().optional(), claimedBy: t.identity().optional(), claimedAt: t.timestamp().optional(), revokedAt: t.timestamp().optional() };
const authSessionRow = { id: t.u64().primaryKey().autoInc(), memberIdentity: t.identity(), sessionKey: t.string(), sessionLabel: t.string(), authMethod: authMethodEnum, issuedAt: t.timestamp(), expiresAt: t.timestamp(), lastSeenAt: t.timestamp(), revokedAt: t.timestamp().optional(), revokeReason: t.string().optional() };
const pipelineRow = { id: t.u64().primaryKey().autoInc(), partyId: t.u64(), ownerId: t.identity(), title: t.string(), legacyYear: t.u32().optional(), opportunityNumber: t.string(), folderNumber: t.string(), folderName: t.string(), sfdcTitle: t.string(), comment: t.string(), ehReference: t.string(), paymentTerms: t.string(), ownerName: t.string(), source: t.string(), sourceNotes: t.string(), deliverySummary: t.string(), status: entityStatusEnum, estimatedValueFils: t.u64(), winProbabilityBps: t.u64(), competitorPresent: t.bool(), oemPriceFils: t.u64(), markupBps: t.u64(), additionalCostsFils: t.u64(), costingApproved: t.bool(), costingApprovedBy: t.identity().optional(), offerTotalFils: t.u64(), offerSentAt: t.timestamp().optional(), lossReason: t.string().optional(), nextFollowUp: t.timestamp().optional(), revision: t.u64(), createdAt: t.timestamp(), updatedAt: t.timestamp() };
const orderRow = { id: t.u64().primaryKey().autoInc(), partyId: t.u64(), pipelineId: t.u64().optional(), status: entityStatusEnum, totalFils: t.u64(), poReference: t.string(), source: t.string(), expectedDelivery: t.timestamp().optional(), createdAt: t.timestamp(), updatedAt: t.timestamp() };
const lineItemRow = { id: t.u64().primaryKey().autoInc(), parentType: t.string(), parentId: t.u64(), description: t.string(), quantity: t.u64(), unitPriceFils: t.u64(), totalPriceFils: t.u64(), fobCostFils: t.u64(), freightCostFils: t.u64(), customsCostFils: t.u64(), insuranceCostFils: t.u64(), handlingCostFils: t.u64(), financeCostFils: t.u64(), marginBps: t.u32(), costPerUnitFils: t.u64() };
const purchaseOrderRow = { id: t.u64().primaryKey().autoInc(), partyId: t.u64(), orderId: t.u64().optional(), poNumber: t.string(), deliveryTerms: t.string(), source: t.string(), status: entityStatusEnum, totalFils: t.u64(), createdBy: t.identity(), createdAt: t.timestamp(), updatedAt: t.timestamp() };
const deliveryNoteRow = { id: t.u64().primaryKey().autoInc(), orderId: t.u64(), partyId: t.u64(), dnNumber: t.string(), status: deliveryStatusEnum, deliveryDate: t.timestamp(), deliveryAddress: t.string(), driverName: t.string(), vehicleNumber: t.string(), receiverName: t.string(), notes: t.string(), createdBy: t.identity(), createdAt: t.timestamp(), updatedAt: t.timestamp() };
const deliveryNoteItemRow = { id: t.u64().primaryKey().autoInc(), deliveryNoteId: t.u64(), lineItemId: t.u64(), quantityDelivered: t.u64(), notes: t.string() };
const goodsReceivedNoteRow = { id: t.u64().primaryKey().autoInc(), purchaseOrderId: t.u64(), grnNumber: t.string(), status: grnStatusEnum, receivedDate: t.timestamp(), receivedBy: t.identity(), inspectionNotes: t.string(), createdAt: t.timestamp() };
const grnItemRow = { id: t.u64().primaryKey().autoInc(), grnId: t.u64(), lineItemId: t.u64(), quantityReceived: t.u64(), quantityAccepted: t.u64(), notes: t.string() };
const moneyEventRow = { id: t.u64().primaryKey().autoInc(), partyId: t.u64(), orderId: t.u64().optional(), deliveryNoteId: t.u64().optional(), kind: moneyEventKindEnum, status: entityStatusEnum, subtotalFils: t.u64(), vatFils: t.u64(), totalFils: t.u64(), reference: t.string(), sourceDate: t.timestamp().optional(), dueDate: t.timestamp().optional(), paidAt: t.timestamp().optional(), createdBy: t.identity(), createdAt: t.timestamp(), updatedAt: t.timestamp() };
const activityLogRow = { id: t.u64().primaryKey().autoInc(), actorId: t.identity(), entityType: t.string(), entityId: t.u64(), action: t.string(), detail: t.string(), followUpDue: t.timestamp().optional(), followUpDone: t.bool(), createdAt: t.timestamp() };
const aiActionRow = { id: t.u64().primaryKey().autoInc(), requestorId: t.identity(), skillName: t.string(), plan: t.string(), status: aiActionStatusEnum, approvedBy: t.identity().optional(), result: t.string(), errorMessage: t.string().optional(), createdAt: t.timestamp(), updatedAt: t.timestamp() };
const docSequenceRow = { id: t.u64().primaryKey().autoInc(), docType: t.string(), year: t.u32(), lastNumber: t.u32() };
const bankTransactionRow = { id: t.u64().primaryKey().autoInc(), bankName: t.string(), transactionDate: t.timestamp(), description: t.string(), amountFils: t.i64(), reference: t.string(), matchedMoneyEventId: t.u64().optional(), matchStatus: bankMatchStatusEnum, importedAt: t.timestamp(), importedBy: t.identity() };
const chatMessageRow = { id: t.u64().primaryKey().autoInc(), memberId: t.identity(), role: t.string(), content: t.string(), skillRequest: t.string().optional(), approvalStatus: t.string().optional(), transitionRequest: t.string().optional(), pipelineContext: t.string().optional(), createdAt: t.timestamp() };
const aiMemoryRow = { id: t.u64().primaryKey().autoInc(), category: t.string(), subject: t.string(), content: t.string(), confidence: t.u32(), source: t.string(), createdBy: t.identity(), createdAt: t.timestamp(), lastRelevantAt: t.timestamp(), expiresAt: t.timestamp().optional() };
const fxRateRow = { id: t.u64().primaryKey().autoInc(), fromCurrency: t.string(), toCurrency: t.string(), rate: t.u64(), rateScale: t.u32(), effectiveDate: t.timestamp(), source: t.string(), createdBy: t.identity(), createdAt: t.timestamp() };
const productRow = { id: t.u64().primaryKey().autoInc(), sku: t.string(), name: t.string(), category: t.string(), supplierPartyId: t.u64().optional(), unitCostFils: t.u64(), unitPriceFils: t.u64(), minMarkupBps: t.u32(), hsCode: t.string(), description: t.string(), isActive: t.bool(), createdAt: t.timestamp(), updatedAt: t.timestamp() };
const stockEntryRow = { id: t.u64().primaryKey().autoInc(), productId: t.u64(), entryType: t.string(), quantity: t.i64(), referencePO: t.string(), referenceGRN: t.string(), notes: t.string(), createdBy: t.identity(), createdAt: t.timestamp() };

const spacetimedb = schema({
  member: table({ public: true }, memberRow),
  accessKey: table({ name: 'access_key', public: true, indexes: [{ accessor: 'access_key_by_key', algorithm: 'btree', columns: ['key'] }, { accessor: 'access_key_by_claimed_by', algorithm: 'btree', columns: ['claimedBy'] }] }, accessKeyRow),
  authSession: table({ name: 'auth_session', public: true, indexes: [{ accessor: 'auth_session_by_member', algorithm: 'btree', columns: ['memberIdentity'] }, { accessor: 'auth_session_by_session_key', algorithm: 'btree', columns: ['sessionKey'] }] }, authSessionRow),
  party: table({ public: true, indexes: [{ accessor: 'party_by_grade', algorithm: 'btree', columns: ['grade'] }, { accessor: 'party_by_customer', algorithm: 'btree', columns: ['isCustomer'] }, { accessor: 'party_by_supplier', algorithm: 'btree', columns: ['isSupplier'] }] }, partyRow),
  contact: table({ public: true, indexes: [{ accessor: 'contact_by_party', algorithm: 'btree', columns: ['partyId'] }] }, contactRow),
  pipeline: table({ public: true, indexes: [{ accessor: 'pipeline_by_party', algorithm: 'btree', columns: ['partyId'] }, { accessor: 'pipeline_by_owner', algorithm: 'btree', columns: ['ownerId'] }, { accessor: 'pipeline_by_status', algorithm: 'btree', columns: ['status'] }] }, pipelineRow),
  order: table({ public: true, indexes: [{ accessor: 'order_by_party', algorithm: 'btree', columns: ['partyId'] }, { accessor: 'order_by_status', algorithm: 'btree', columns: ['status'] }, { accessor: 'order_by_pipeline', algorithm: 'btree', columns: ['pipelineId'] }] }, orderRow),
  lineItem: table({ name: 'line_item', public: true, indexes: [{ accessor: 'line_item_by_parent', algorithm: 'btree', columns: ['parentId'] }] }, lineItemRow),
  purchaseOrder: table({ name: 'purchase_order', public: true, indexes: [{ accessor: 'po_by_party', algorithm: 'btree', columns: ['partyId'] }, { accessor: 'po_by_status', algorithm: 'btree', columns: ['status'] }] }, purchaseOrderRow),
  deliveryNote: table({ name: 'delivery_note', public: true, indexes: [{ accessor: 'dn_by_order', algorithm: 'btree', columns: ['orderId'] }, { accessor: 'dn_by_party', algorithm: 'btree', columns: ['partyId'] }, { accessor: 'dn_by_status', algorithm: 'btree', columns: ['status'] }] }, deliveryNoteRow),
  deliveryNoteItem: table({ name: 'delivery_note_item', public: true, indexes: [{ accessor: 'dn_item_by_dn', algorithm: 'btree', columns: ['deliveryNoteId'] }, { accessor: 'dn_item_by_line_item', algorithm: 'btree', columns: ['lineItemId'] }] }, deliveryNoteItemRow),
  goodsReceivedNote: table({ name: 'goods_received_note', public: true, indexes: [{ accessor: 'grn_by_po', algorithm: 'btree', columns: ['purchaseOrderId'] }, { accessor: 'grn_by_status', algorithm: 'btree', columns: ['status'] }] }, goodsReceivedNoteRow),
  grnItem: table({ name: 'grn_item', public: true, indexes: [{ accessor: 'grn_item_by_grn', algorithm: 'btree', columns: ['grnId'] }, { accessor: 'grn_item_by_line_item', algorithm: 'btree', columns: ['lineItemId'] }] }, grnItemRow),
  moneyEvent: table({ name: 'money_event', public: true, indexes: [{ accessor: 'money_by_party', algorithm: 'btree', columns: ['partyId'] }, { accessor: 'money_by_kind', algorithm: 'btree', columns: ['kind'] }, { accessor: 'money_by_status', algorithm: 'btree', columns: ['status'] }, { accessor: 'money_by_order', algorithm: 'btree', columns: ['orderId'] }, { accessor: 'money_by_delivery_note', algorithm: 'btree', columns: ['deliveryNoteId'] }] }, moneyEventRow),
  activityLog: table({ name: 'activity_log', public: true, indexes: [{ accessor: 'activity_by_entity', algorithm: 'btree', columns: ['entityId'] }, { accessor: 'activity_by_actor', algorithm: 'btree', columns: ['actorId'] }] }, activityLogRow),
  aiAction: table({ name: 'ai_action', public: true, indexes: [{ accessor: 'ai_by_status', algorithm: 'btree', columns: ['status'] }, { accessor: 'ai_by_requestor', algorithm: 'btree', columns: ['requestorId'] }] }, aiActionRow),
  docSequence: table({ name: 'doc_sequence', public: true, indexes: [{ accessor: 'seq_by_type_year', algorithm: 'btree', columns: ['docType', 'year'] }] }, docSequenceRow),
  bankTransaction: table({ name: 'bank_transaction', public: true, indexes: [{ accessor: 'bank_by_match_status', algorithm: 'btree', columns: ['matchStatus'] }, { accessor: 'bank_by_bank_name', algorithm: 'btree', columns: ['bankName'] }, { accessor: 'bank_by_date', algorithm: 'btree', columns: ['transactionDate'] }] }, bankTransactionRow),
  chatMessage: table({ name: 'chat_message', public: true, indexes: [{ accessor: 'chat_by_member', algorithm: 'btree', columns: ['memberId'] }, { accessor: 'chat_by_created_at', algorithm: 'btree', columns: ['createdAt'] }] }, chatMessageRow),
  aiMemory: table({ name: 'ai_memory', public: true, indexes: [{ accessor: 'memory_by_category', algorithm: 'btree', columns: ['category'] }, { accessor: 'memory_by_created_by', algorithm: 'btree', columns: ['createdBy'] }, { accessor: 'memory_by_subject', algorithm: 'btree', columns: ['subject'] }] }, aiMemoryRow),
  fxRate: table({ name: 'fx_rate', public: true, indexes: [{ accessor: 'fx_by_pair', algorithm: 'btree', columns: ['fromCurrency', 'toCurrency'] }, { accessor: 'fx_by_date', algorithm: 'btree', columns: ['effectiveDate'] }] }, fxRateRow),
  product: table({ public: true, indexes: [{ accessor: 'product_by_sku', algorithm: 'btree', columns: ['sku'] }, { accessor: 'product_by_category', algorithm: 'btree', columns: ['category'] }, { accessor: 'product_by_supplier', algorithm: 'btree', columns: ['supplierPartyId'] }] }, productRow),
  stockEntry: table({ name: 'stock_entry', public: true, indexes: [{ accessor: 'stock_by_product', algorithm: 'btree', columns: ['productId'] }, { accessor: 'stock_by_type', algorithm: 'btree', columns: ['entryType'] }] }, stockEntryRow),
});
export default spacetimedb;

function requireMember(ctx: any) { const member = ctx.db.member.identity.find(ctx.sender); if (!member) throw new Error('You must join the team first - call join_member'); return member as { role: UserRole }; }
function requireRole(caller: { role: UserRole }, ...roles: string[]) { if (!roles.includes(caller.role.tag)) throw new Error(`Action requires role: ${roles.join(' or ')}. You are: ${caller.role.tag}`); }
function computeOutstanding(partyId: bigint, ctx: any) { let invoiced = 0n; let paid = 0n; for (const evt of ctx.db.moneyEvent.money_by_party.filter(partyId)) { if (evt.kind.tag === 'CustomerInvoice') invoiced += evt.totalFils; else if (evt.kind.tag === 'CustomerPayment') paid += evt.totalFils; } return invoiced > paid ? invoiced - paid : 0n; }

export const bootstrap_admin = spacetimedb.reducer({ name: 'bootstrap_admin' }, { nickname: t.string(), fullName: t.string(), email: t.string() }, (ctx, args) => { bootstrapAdminImpl(ctx, args); });
export const issue_access_key = spacetimedb.reducer({ name: 'issue_access_key' }, { key: t.string(), role: userRoleEnum, assignedEmail: t.string(), assignedName: t.string(), notes: t.string(), expiresAt: t.timestamp().optional() }, (ctx, args) => { const caller = requireMember(ctx); issueAccessKeyImpl(ctx, caller, requireRole, args); });
export const redeem_access_key = spacetimedb.reducer({ name: 'redeem_access_key' }, { key: t.string(), nickname: t.string(), fullName: t.string(), email: t.string() }, (ctx, args) => { redeemAccessKeyImpl(ctx, args); });
export const upsert_auth_session = spacetimedb.reducer({ name: 'upsert_auth_session' }, { sessionKey: t.string(), sessionLabel: t.string(), ttlHours: t.u64().optional() }, (ctx, args) => { const member = requireMember(ctx) as any; upsertAuthSessionImpl(ctx, member, args); });
export const revoke_auth_session = spacetimedb.reducer({ name: 'revoke_auth_session' }, { sessionKey: t.string(), revokeReason: t.string().optional() }, (ctx, args) => { const caller = requireMember(ctx); revokeAuthSessionImpl(ctx, caller, requireRole, args); });
export const join_member = spacetimedb.reducer({ nickname: t.string(), fullName: t.string(), role: userRoleEnum }, (ctx, args) => { if (ctx.db.member.identity.find(ctx.sender)) throw new Error('Already registered'); if (hasAnyMembers(ctx)) throw new Error('Open join_member is disabled - redeem an access key instead'); ctx.db.member.insert({ identity: ctx.sender, nickname: args.nickname.trim(), fullName: args.fullName.trim(), email: '', role: { tag: 'Admin' } as UserRole, authMethod: { tag: 'Bootstrap' } as AuthMethod, accessKeyId: undefined, joinedAt: ctx.timestamp, lastLoginAt: ctx.timestamp, updatedAt: ctx.timestamp }); });
export const upsert_party = spacetimedb.reducer({ name: 'upsert_party' }, { id: t.u64(), name: t.string(), code: t.string().optional(), category: t.string().optional(), isCustomer: t.bool(), isSupplier: t.bool(), grade: customerGradeEnum, creditLimitFils: t.u64(), paymentTermsDays: t.u64(), productTypes: t.string(), annualGoalFils: t.u64(), city: t.string().optional(), country: t.string().optional(), phone: t.string().optional(), email: t.string().optional(), source: t.string().optional(), active2024: t.bool().optional(), active2025: t.bool().optional(), active2026: t.bool().optional(), notes: t.string(), bankIban: t.string(), bankSwift: t.string(), bankAccountName: t.string() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Sales'); upsertPartyImpl(ctx, args); });
export const upsert_contact = spacetimedb.reducer({ name: 'upsert_contact' }, { id: t.u64(), partyId: t.u64(), name: t.string(), designation: t.string(), phone: t.string(), email: t.string(), isWhatsApp: t.bool() }, (ctx, args) => { requireMember(ctx); upsertContactImpl(ctx, args); });
export const advance_pipeline = spacetimedb.reducer({ name: 'advance_pipeline' }, { id: t.u64(), partyId: t.u64(), title: t.string(), legacyYear: t.u32().optional(), opportunityNumber: t.string().optional(), folderNumber: t.string().optional(), folderName: t.string().optional(), sfdcTitle: t.string().optional(), comment: t.string().optional(), ehReference: t.string().optional(), paymentTerms: t.string().optional(), ownerName: t.string().optional(), source: t.string().optional(), sourceNotes: t.string().optional(), deliverySummary: t.string().optional(), newStatus: entityStatusEnum, estimatedValueFils: t.u64(), winProbabilityBps: t.u64(), competitorPresent: t.bool(), oemPriceFils: t.u64(), markupBps: t.u64(), additionalCostsFils: t.u64(), costingApproved: t.bool(), offerSentAt: t.timestamp().optional(), lossReason: t.string().optional(), nextFollowUp: t.timestamp().optional() }, (ctx, args) => { const caller = requireMember(ctx); if (args.costingApproved) { if (args.markupBps < 1200n) requireRole(caller, 'Admin'); else if (args.markupBps < 2000n) requireRole(caller, 'Admin', 'Manager'); } advancePipelineImpl(ctx, args); });
export const manage_order = spacetimedb.reducer({ name: 'manage_order' }, { id: t.u64(), partyId: t.u64(), pipelineId: t.u64().optional(), source: t.string().optional(), newStatus: entityStatusEnum, totalFils: t.u64(), poReference: t.string(), expectedDelivery: t.timestamp().optional() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Sales', 'Operations'); manageOrderImpl(ctx, args); });
export const manage_purchase_order = spacetimedb.reducer({ name: 'manage_purchase_order' }, { id: t.u64(), partyId: t.u64(), orderId: t.u64().optional(), deliveryTerms: t.string().optional(), source: t.string().optional(), newStatus: entityStatusEnum, totalFils: t.u64() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); managePurchaseOrderImpl(ctx, args); });
export const add_line_item = spacetimedb.reducer({ name: 'add_line_item' }, { parentType: t.string(), parentId: t.u64(), description: t.string(), quantity: t.u64(), unitPriceFils: t.u64(), fobCostFils: t.u64().optional(), freightCostFils: t.u64().optional(), customsCostFils: t.u64().optional(), insuranceCostFils: t.u64().optional(), handlingCostFils: t.u64().optional(), financeCostFils: t.u64().optional(), marginBps: t.u32().optional(), costPerUnitFils: t.u64().optional() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Sales', 'Operations', 'Accountant'); addLineItemImpl(ctx, args); });
export const create_delivery_note = spacetimedb.reducer({ name: 'create_delivery_note' }, { orderId: t.u64(), partyId: t.u64(), deliveryAddress: t.string(), driverName: t.string(), vehicleNumber: t.string() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); createDeliveryNoteImpl(ctx, args); });
export const advance_delivery_note = spacetimedb.reducer({ name: 'advance_delivery_note' }, { id: t.u64(), newStatus: deliveryStatusEnum, receiverName: t.string().optional(), notes: t.string().optional() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); advanceDeliveryNoteImpl(ctx, args); });
export const add_delivery_note_item = spacetimedb.reducer({ name: 'add_delivery_note_item' }, { deliveryNoteId: t.u64(), lineItemId: t.u64(), quantityDelivered: t.u64(), notes: t.string() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); addDeliveryNoteItemImpl(ctx, args); });
export const create_grn = spacetimedb.reducer({ name: 'create_grn' }, { purchaseOrderId: t.u64(), receivedDate: t.timestamp(), inspectionNotes: t.string() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); createGrnImpl(ctx, args); });
export const advance_grn = spacetimedb.reducer({ name: 'advance_grn' }, { id: t.u64(), newStatus: grnStatusEnum, inspectionNotes: t.string().optional() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); advanceGrnImpl(ctx, args); });
export const add_grn_item = spacetimedb.reducer({ name: 'add_grn_item' }, { grnId: t.u64(), lineItemId: t.u64(), quantityReceived: t.u64(), quantityAccepted: t.u64(), notes: t.string() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); addGrnItemImpl(ctx, args); });
export const convert_pipeline_to_order = spacetimedb.reducer({ name: 'convert_pipeline_to_order' }, { pipelineId: t.u64(), poReference: t.string(), expectedDelivery: t.timestamp().optional() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Sales', 'Operations'); convertPipelineToOrderImpl(ctx, args); });
export const record_money_event = spacetimedb.reducer({ name: 'record_money_event' }, { partyId: t.u64(), orderId: t.u64().optional(), deliveryNoteId: t.u64().optional(), kind: moneyEventKindEnum, subtotalFils: t.u64(), reference: t.string(), sourceDate: t.timestamp().optional(), dueDate: t.timestamp().optional() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Accountant'); recordMoneyEventImpl(ctx, args); });
export const log_activity = spacetimedb.reducer({ name: 'log_activity' }, { entityType: t.string(), entityId: t.u64(), action: t.string(), detail: t.string(), followUpDue: t.timestamp().optional() }, (ctx, args) => { requireMember(ctx); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: args.entityType, entityId: args.entityId, action: args.action, detail: args.detail, followUpDue: args.followUpDue, followUpDone: false, createdAt: ctx.timestamp }); });
export const propose_ai_action = spacetimedb.reducer({ name: 'propose_ai_action' }, { skillName: t.string(), plan: t.string() }, (ctx, args) => { requireMember(ctx); ctx.db.aiAction.insert({ id: 0n, requestorId: ctx.sender, skillName: args.skillName, plan: args.plan, status: { tag: 'Proposed' } as AiActionStatus, approvedBy: undefined, result: '', errorMessage: undefined, createdAt: ctx.timestamp, updatedAt: ctx.timestamp }); });
export const resolve_ai_action = spacetimedb.reducer({ name: 'resolve_ai_action' }, { actionId: t.u64(), approve: t.bool(), result: t.string() }, (ctx, args) => { const caller = requireMember(ctx); if (args.approve) requireRole(caller, 'Admin', 'Manager'); resolveAiActionImpl(ctx, args); });
export const next_doc_number = spacetimedb.reducer({ name: 'next_doc_number' }, { docType: t.string(), year: t.u32() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Accountant'); const validDocTypes = ['invoice', 'quotation', 'statement', 'purchase_order', 'delivery_note', 'grn']; if (!validDocTypes.includes(args.docType)) throw new Error(`Unknown docType "${args.docType}". Valid types: ${validDocTypes.join(', ')}`); const formatted = issueDocNumber(ctx, args.docType, args.year); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'doc_sequence', entityId: BigInt(args.year), action: args.docType, detail: `Next document number issued: ${formatted}`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); });
export const import_bank_transaction = spacetimedb.reducer({ name: 'import_bank_transaction' }, { bankName: t.string(), transactionDate: t.timestamp(), description: t.string(), amountFils: t.i64(), reference: t.string() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Accountant'); const row = ctx.db.bankTransaction.insert({ id: 0n, bankName: args.bankName, transactionDate: args.transactionDate, description: args.description, amountFils: args.amountFils, reference: args.reference, matchedMoneyEventId: undefined, matchStatus: { tag: 'Unmatched' } as BankMatchStatus, importedAt: ctx.timestamp, importedBy: ctx.sender }); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'bank_transaction', entityId: row.id, action: 'imported', detail: `Bank txn #${row.id} imported`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); });
export const match_bank_transaction = spacetimedb.reducer({ name: 'match_bank_transaction' }, { bankTransactionId: t.u64(), moneyEventId: t.u64() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Accountant'); const bankTxn = ctx.db.bankTransaction.id.find(args.bankTransactionId); if (!bankTxn) throw new Error(`Bank transaction #${args.bankTransactionId} not found`); const moneyEvent = ctx.db.moneyEvent.id.find(args.moneyEventId); if (!moneyEvent) throw new Error(`Money event #${args.moneyEventId} not found`); ctx.db.bankTransaction.id.update({ ...bankTxn, matchedMoneyEventId: args.moneyEventId, matchStatus: { tag: 'Matched' } as BankMatchStatus }); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'bank_transaction', entityId: args.bankTransactionId, action: 'matched', detail: `Bank txn #${args.bankTransactionId} matched to money event #${args.moneyEventId}`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); });
export const unmatch_bank_transaction = spacetimedb.reducer({ name: 'unmatch_bank_transaction' }, { bankTransactionId: t.u64() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Accountant'); const bankTxn = ctx.db.bankTransaction.id.find(args.bankTransactionId); if (!bankTxn) throw new Error(`Bank transaction #${args.bankTransactionId} not found`); ctx.db.bankTransaction.id.update({ ...bankTxn, matchedMoneyEventId: undefined, matchStatus: { tag: 'Unmatched' } as BankMatchStatus }); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'bank_transaction', entityId: args.bankTransactionId, action: 'unmatched', detail: `Bank txn #${args.bankTransactionId} reset to unmatched`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); });
export const dispute_bank_transaction = spacetimedb.reducer({ name: 'dispute_bank_transaction' }, { bankTransactionId: t.u64() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Accountant'); const bankTxn = ctx.db.bankTransaction.id.find(args.bankTransactionId); if (!bankTxn) throw new Error(`Bank transaction #${args.bankTransactionId} not found`); ctx.db.bankTransaction.id.update({ ...bankTxn, matchedMoneyEventId: undefined, matchStatus: { tag: 'Disputed' } as BankMatchStatus }); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'bank_transaction', entityId: args.bankTransactionId, action: 'disputed', detail: `Bank txn #${args.bankTransactionId} marked disputed`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); });
export const save_chat_message = spacetimedb.reducer({ name: 'save_chat_message' }, { role: t.string(), content: t.string(), skillRequest: t.string().optional(), approvalStatus: t.string().optional(), transitionRequest: t.string().optional(), pipelineContext: t.string().optional() }, (ctx, args) => { saveChatMessageImpl(ctx, args, requireMember); });
export const save_ai_memory = spacetimedb.reducer({ name: 'save_ai_memory' }, { category: t.string(), subject: t.string(), content: t.string(), confidence: t.u32(), source: t.string() }, (ctx, args) => { saveAiMemoryImpl(ctx, args, requireMember); });
export const delete_ai_memory = spacetimedb.reducer({ name: 'delete_ai_memory' }, { memoryId: t.u64() }, (ctx, args) => { deleteAiMemoryImpl(ctx, args, requireMember, requireRole); });
export const record_fx_rate = spacetimedb.reducer({ name: 'record_fx_rate' }, { fromCurrency: t.string(), toCurrency: t.string(), rate: t.u64(), rateScale: t.u32(), effectiveDate: t.timestamp(), source: t.string() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Accountant'); const row = ctx.db.fxRate.insert({ id: 0n, fromCurrency: args.fromCurrency.toUpperCase(), toCurrency: args.toCurrency.toUpperCase(), rate: args.rate, rateScale: args.rateScale, effectiveDate: args.effectiveDate, source: args.source, createdBy: ctx.sender, createdAt: ctx.timestamp }); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'fx_rate', entityId: row.id, action: 'record_fx_rate', detail: `FX rate ${args.fromCurrency}/${args.toCurrency} = ${Number(args.rate)}/${args.rateScale}`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); });
export const upsert_product = spacetimedb.reducer({ name: 'upsert_product' }, { id: t.u64(), sku: t.string(), name: t.string(), category: t.string(), supplierPartyId: t.u64().optional(), unitCostFils: t.u64(), unitPriceFils: t.u64(), minMarkupBps: t.u32(), hsCode: t.string(), description: t.string(), isActive: t.bool() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); if (args.id === 0n) { const row = ctx.db.product.insert({ id: 0n, sku: args.sku.trim(), name: args.name.trim(), category: args.category, supplierPartyId: args.supplierPartyId, unitCostFils: args.unitCostFils, unitPriceFils: args.unitPriceFils, minMarkupBps: args.minMarkupBps, hsCode: args.hsCode, description: args.description, isActive: args.isActive, createdAt: ctx.timestamp, updatedAt: ctx.timestamp }); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'product', entityId: row.id, action: 'upsert_product', detail: `Created product: ${row.name} (${row.sku})`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); } else { const existing = ctx.db.product.id.find(args.id); if (!existing) throw new Error(`Product #${args.id} not found`); ctx.db.product.id.update({ ...existing, sku: args.sku.trim(), name: args.name.trim(), category: args.category, supplierPartyId: args.supplierPartyId, unitCostFils: args.unitCostFils, unitPriceFils: args.unitPriceFils, minMarkupBps: args.minMarkupBps, hsCode: args.hsCode, description: args.description, isActive: args.isActive, updatedAt: ctx.timestamp }); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'product', entityId: args.id, action: 'upsert_product', detail: `Updated product: ${args.name} (${args.sku})`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); } });
export const record_stock_movement = spacetimedb.reducer({ name: 'record_stock_movement' }, { productId: t.u64(), entryType: t.string(), quantity: t.i64(), referencePO: t.string(), referenceGRN: t.string(), notes: t.string() }, (ctx, args) => { const caller = requireMember(ctx); requireRole(caller, 'Admin', 'Manager', 'Operations'); const product = ctx.db.product.id.find(args.productId); if (!product) throw new Error(`Product #${args.productId} not found`); const validTypes = ['received', 'shipped', 'adjustment', 'return']; if (!validTypes.includes(args.entryType)) throw new Error(`Invalid entry type "${args.entryType}". Must be one of: ${validTypes.join(', ')}`); const row = ctx.db.stockEntry.insert({ id: 0n, productId: args.productId, entryType: args.entryType, quantity: args.quantity, referencePO: args.referencePO, referenceGRN: args.referenceGRN, notes: args.notes, createdBy: ctx.sender, createdAt: ctx.timestamp }); ctx.db.activityLog.insert({ id: 0n, actorId: ctx.sender, entityType: 'stock_entry', entityId: row.id, action: 'record_stock_movement', detail: `Stock ${args.entryType}: ${product.name} qty ${args.quantity}`, followUpDue: undefined, followUpDone: false, createdAt: ctx.timestamp }); });
