// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  parentType: __t.string(),
  parentId: __t.u64(),
  description: __t.string(),
  quantity: __t.u64(),
  unitPriceFils: __t.u64(),
  fobCostFils: __t.option(__t.u64()),
  freightCostFils: __t.option(__t.u64()),
  customsCostFils: __t.option(__t.u64()),
  insuranceCostFils: __t.option(__t.u64()),
  handlingCostFils: __t.option(__t.u64()),
  financeCostFils: __t.option(__t.u64()),
  marginBps: __t.option(__t.u32()),
  costPerUnitFils: __t.option(__t.u64()),
};
