// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  memberId: __t.identity().name("member_id"),
  role: __t.string(),
  content: __t.string(),
  skillRequest: __t.option(__t.string()).name("skill_request"),
  approvalStatus: __t.option(__t.string()).name("approval_status"),
  transitionRequest: __t.option(__t.string()).name("transition_request"),
  pipelineContext: __t.option(__t.string()).name("pipeline_context"),
  createdAt: __t.timestamp().name("created_at"),
});
