// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GrnStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  purchaseOrderId: __t.u64().name("purchase_order_id"),
  grnNumber: __t.string().name("grn_number"),
  get status() {
    return GrnStatus;
  },
  receivedDate: __t.timestamp().name("received_date"),
  receivedBy: __t.identity().name("received_by"),
  inspectionNotes: __t.string().name("inspection_notes"),
  createdAt: __t.timestamp().name("created_at"),
});
