// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 5836c268a7307f864b33636357b0869ecc40bc0a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddDeliveryNoteItemReducer from "./add_delivery_note_item_reducer";
import AddGrnItemReducer from "./add_grn_item_reducer";
import AddLineItemReducer from "./add_line_item_reducer";
import AdvanceDeliveryNoteReducer from "./advance_delivery_note_reducer";
import AdvanceGrnReducer from "./advance_grn_reducer";
import AdvancePipelineReducer from "./advance_pipeline_reducer";
import BootstrapAdminReducer from "./bootstrap_admin_reducer";
import ConvertPipelineToOrderReducer from "./convert_pipeline_to_order_reducer";
import CreateDeliveryNoteReducer from "./create_delivery_note_reducer";
import CreateGrnReducer from "./create_grn_reducer";
import DeleteAiMemoryReducer from "./delete_ai_memory_reducer";
import DisputeBankTransactionReducer from "./dispute_bank_transaction_reducer";
import ImportBankTransactionReducer from "./import_bank_transaction_reducer";
import IssueAccessKeyReducer from "./issue_access_key_reducer";
import JoinMemberReducer from "./join_member_reducer";
import LogActivityReducer from "./log_activity_reducer";
import ManageOrderReducer from "./manage_order_reducer";
import ManagePurchaseOrderReducer from "./manage_purchase_order_reducer";
import MatchBankTransactionReducer from "./match_bank_transaction_reducer";
import NextDocNumberReducer from "./next_doc_number_reducer";
import ProposeAiActionReducer from "./propose_ai_action_reducer";
import RecordFxRateReducer from "./record_fx_rate_reducer";
import RecordMoneyEventReducer from "./record_money_event_reducer";
import RecordStockMovementReducer from "./record_stock_movement_reducer";
import RedeemAccessKeyReducer from "./redeem_access_key_reducer";
import ResolveAiActionReducer from "./resolve_ai_action_reducer";
import RevokeAuthSessionReducer from "./revoke_auth_session_reducer";
import SaveAiMemoryReducer from "./save_ai_memory_reducer";
import SaveChatMessageReducer from "./save_chat_message_reducer";
import UnmatchBankTransactionReducer from "./unmatch_bank_transaction_reducer";
import UpsertAuthSessionReducer from "./upsert_auth_session_reducer";
import UpsertContactReducer from "./upsert_contact_reducer";
import UpsertPartyReducer from "./upsert_party_reducer";
import UpsertProductReducer from "./upsert_product_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccessKeyRow from "./access_key_table";
import ActivityLogRow from "./activity_log_table";
import AiActionRow from "./ai_action_table";
import AiMemoryRow from "./ai_memory_table";
import AuthSessionRow from "./auth_session_table";
import BankTransactionRow from "./bank_transaction_table";
import ChatMessageRow from "./chat_message_table";
import ContactRow from "./contact_table";
import DeliveryNoteRow from "./delivery_note_table";
import DeliveryNoteItemRow from "./delivery_note_item_table";
import DocSequenceRow from "./doc_sequence_table";
import FxRateRow from "./fx_rate_table";
import GoodsReceivedNoteRow from "./goods_received_note_table";
import GrnItemRow from "./grn_item_table";
import LineItemRow from "./line_item_table";
import MemberRow from "./member_table";
import MoneyEventRow from "./money_event_table";
import OrderRow from "./order_table";
import PartyRow from "./party_table";
import PipelineRow from "./pipeline_table";
import ProductRow from "./product_table";
import PurchaseOrderRow from "./purchase_order_table";
import StockEntryRow from "./stock_entry_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  accessKey: __table({
    name: 'access_key',
    indexes: [
      { name: 'access_key_by_claimed_by', algorithm: 'btree', columns: [
        'claimedBy',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'access_key_by_key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'access_key_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AccessKeyRow),
  activityLog: __table({
    name: 'activity_log',
    indexes: [
      { name: 'activity_by_actor', algorithm: 'btree', columns: [
        'actorId',
      ] },
      { name: 'activity_by_entity', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'activity_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActivityLogRow),
  aiAction: __table({
    name: 'ai_action',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'ai_by_requestor', algorithm: 'btree', columns: [
        'requestorId',
      ] },
      { name: 'ai_by_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'ai_action_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AiActionRow),
  aiMemory: __table({
    name: 'ai_memory',
    indexes: [
      { name: 'memory_by_category', algorithm: 'btree', columns: [
        'category',
      ] },
      { name: 'memory_by_created_by', algorithm: 'btree', columns: [
        'createdBy',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'memory_by_subject', algorithm: 'btree', columns: [
        'subject',
      ] },
    ],
    constraints: [
      { name: 'ai_memory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AiMemoryRow),
  authSession: __table({
    name: 'auth_session',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'auth_session_by_member', algorithm: 'btree', columns: [
        'memberIdentity',
      ] },
      { name: 'auth_session_by_session_key', algorithm: 'btree', columns: [
        'sessionKey',
      ] },
    ],
    constraints: [
      { name: 'auth_session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AuthSessionRow),
  bankTransaction: __table({
    name: 'bank_transaction',
    indexes: [
      { name: 'bank_by_bank_name', algorithm: 'btree', columns: [
        'bankName',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'bank_by_match_status', algorithm: 'btree', columns: [
        'matchStatus',
      ] },
      { name: 'bank_by_date', algorithm: 'btree', columns: [
        'transactionDate',
      ] },
    ],
    constraints: [
      { name: 'bank_transaction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BankTransactionRow),
  chatMessage: __table({
    name: 'chat_message',
    indexes: [
      { name: 'chat_by_created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'chat_by_member', algorithm: 'btree', columns: [
        'memberId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  contact: __table({
    name: 'contact',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'contact_by_party', algorithm: 'btree', columns: [
        'partyId',
      ] },
    ],
    constraints: [
      { name: 'contact_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ContactRow),
  deliveryNote: __table({
    name: 'delivery_note',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'dn_by_order', algorithm: 'btree', columns: [
        'orderId',
      ] },
      { name: 'dn_by_party', algorithm: 'btree', columns: [
        'partyId',
      ] },
      { name: 'dn_by_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'delivery_note_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DeliveryNoteRow),
  deliveryNoteItem: __table({
    name: 'delivery_note_item',
    indexes: [
      { name: 'dn_item_by_dn', algorithm: 'btree', columns: [
        'deliveryNoteId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'dn_item_by_line_item', algorithm: 'btree', columns: [
        'lineItemId',
      ] },
    ],
    constraints: [
      { name: 'delivery_note_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DeliveryNoteItemRow),
  docSequence: __table({
    name: 'doc_sequence',
    indexes: [
      { name: 'seq_by_type_year', algorithm: 'btree', columns: [
        'docType',
        'year',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'doc_sequence_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DocSequenceRow),
  fxRate: __table({
    name: 'fx_rate',
    indexes: [
      { name: 'fx_by_date', algorithm: 'btree', columns: [
        'effectiveDate',
      ] },
      { name: 'fx_by_pair', algorithm: 'btree', columns: [
        'fromCurrency',
        'toCurrency',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'fx_rate_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FxRateRow),
  goodsReceivedNote: __table({
    name: 'goods_received_note',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'grn_by_po', algorithm: 'btree', columns: [
        'purchaseOrderId',
      ] },
      { name: 'grn_by_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'goods_received_note_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GoodsReceivedNoteRow),
  grnItem: __table({
    name: 'grn_item',
    indexes: [
      { name: 'grn_item_by_grn', algorithm: 'btree', columns: [
        'grnId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'grn_item_by_line_item', algorithm: 'btree', columns: [
        'lineItemId',
      ] },
    ],
    constraints: [
      { name: 'grn_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GrnItemRow),
  lineItem: __table({
    name: 'line_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'line_item_by_parent', algorithm: 'btree', columns: [
        'parentId',
      ] },
    ],
    constraints: [
      { name: 'line_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LineItemRow),
  member: __table({
    name: 'member',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'member_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, MemberRow),
  moneyEvent: __table({
    name: 'money_event',
    indexes: [
      { name: 'money_by_delivery_note', algorithm: 'btree', columns: [
        'deliveryNoteId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'money_by_kind', algorithm: 'btree', columns: [
        'kind',
      ] },
      { name: 'money_by_order', algorithm: 'btree', columns: [
        'orderId',
      ] },
      { name: 'money_by_party', algorithm: 'btree', columns: [
        'partyId',
      ] },
      { name: 'money_by_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'money_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MoneyEventRow),
  order: __table({
    name: 'order',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'order_by_party', algorithm: 'btree', columns: [
        'partyId',
      ] },
      { name: 'order_by_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'order_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrderRow),
  party: __table({
    name: 'party',
    indexes: [
      { name: 'party_by_grade', algorithm: 'btree', columns: [
        'grade',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'party_by_customer', algorithm: 'btree', columns: [
        'isCustomer',
      ] },
      { name: 'party_by_supplier', algorithm: 'btree', columns: [
        'isSupplier',
      ] },
    ],
    constraints: [
      { name: 'party_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyRow),
  pipeline: __table({
    name: 'pipeline',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'pipeline_by_owner', algorithm: 'btree', columns: [
        'ownerId',
      ] },
      { name: 'pipeline_by_party', algorithm: 'btree', columns: [
        'partyId',
      ] },
      { name: 'pipeline_by_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'pipeline_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PipelineRow),
  product: __table({
    name: 'product',
    indexes: [
      { name: 'product_by_category', algorithm: 'btree', columns: [
        'category',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'product_by_sku', algorithm: 'btree', columns: [
        'sku',
      ] },
      { name: 'product_by_supplier', algorithm: 'btree', columns: [
        'supplierPartyId',
      ] },
    ],
    constraints: [
      { name: 'product_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProductRow),
  purchaseOrder: __table({
    name: 'purchase_order',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'po_by_party', algorithm: 'btree', columns: [
        'partyId',
      ] },
      { name: 'po_by_status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'purchase_order_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PurchaseOrderRow),
  stockEntry: __table({
    name: 'stock_entry',
    indexes: [
      { name: 'stock_by_type', algorithm: 'btree', columns: [
        'entryType',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'stock_by_product', algorithm: 'btree', columns: [
        'productId',
      ] },
    ],
    constraints: [
      { name: 'stock_entry_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StockEntryRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_delivery_note_item", AddDeliveryNoteItemReducer),
  __reducerSchema("add_grn_item", AddGrnItemReducer),
  __reducerSchema("add_line_item", AddLineItemReducer),
  __reducerSchema("advance_delivery_note", AdvanceDeliveryNoteReducer),
  __reducerSchema("advance_grn", AdvanceGrnReducer),
  __reducerSchema("advance_pipeline", AdvancePipelineReducer),
  __reducerSchema("bootstrap_admin", BootstrapAdminReducer),
  __reducerSchema("convert_pipeline_to_order", ConvertPipelineToOrderReducer),
  __reducerSchema("create_delivery_note", CreateDeliveryNoteReducer),
  __reducerSchema("create_grn", CreateGrnReducer),
  __reducerSchema("delete_ai_memory", DeleteAiMemoryReducer),
  __reducerSchema("dispute_bank_transaction", DisputeBankTransactionReducer),
  __reducerSchema("import_bank_transaction", ImportBankTransactionReducer),
  __reducerSchema("issue_access_key", IssueAccessKeyReducer),
  __reducerSchema("join_member", JoinMemberReducer),
  __reducerSchema("log_activity", LogActivityReducer),
  __reducerSchema("manage_order", ManageOrderReducer),
  __reducerSchema("manage_purchase_order", ManagePurchaseOrderReducer),
  __reducerSchema("match_bank_transaction", MatchBankTransactionReducer),
  __reducerSchema("next_doc_number", NextDocNumberReducer),
  __reducerSchema("propose_ai_action", ProposeAiActionReducer),
  __reducerSchema("record_fx_rate", RecordFxRateReducer),
  __reducerSchema("record_money_event", RecordMoneyEventReducer),
  __reducerSchema("record_stock_movement", RecordStockMovementReducer),
  __reducerSchema("redeem_access_key", RedeemAccessKeyReducer),
  __reducerSchema("resolve_ai_action", ResolveAiActionReducer),
  __reducerSchema("revoke_auth_session", RevokeAuthSessionReducer),
  __reducerSchema("save_ai_memory", SaveAiMemoryReducer),
  __reducerSchema("save_chat_message", SaveChatMessageReducer),
  __reducerSchema("unmatch_bank_transaction", UnmatchBankTransactionReducer),
  __reducerSchema("upsert_auth_session", UpsertAuthSessionReducer),
  __reducerSchema("upsert_contact", UpsertContactReducer),
  __reducerSchema("upsert_party", UpsertPartyReducer),
  __reducerSchema("upsert_product", UpsertProductReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

