// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  parentType: __t.string().name("parent_type"),
  parentId: __t.u64().name("parent_id"),
  description: __t.string(),
  quantity: __t.u64(),
  unitPriceFils: __t.u64().name("unit_price_fils"),
  totalPriceFils: __t.u64().name("total_price_fils"),
  fobCostFils: __t.u64().name("fob_cost_fils"),
  freightCostFils: __t.u64().name("freight_cost_fils"),
  customsCostFils: __t.u64().name("customs_cost_fils"),
  insuranceCostFils: __t.u64().name("insurance_cost_fils"),
  handlingCostFils: __t.u64().name("handling_cost_fils"),
  financeCostFils: __t.u64().name("finance_cost_fils"),
  marginBps: __t.u32().name("margin_bps"),
  costPerUnitFils: __t.u64().name("cost_per_unit_fils"),
});
