// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  EntityStatus,
} from "./types";

export default {
  id: __t.u64(),
  partyId: __t.u64(),
  orderId: __t.option(__t.u64()),
  deliveryTerms: __t.option(__t.string()),
  get newStatus() {
    return EntityStatus;
  },
  totalFils: __t.u64(),
};
