// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  UserRole,
  AuthMethod,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  nickname: __t.string(),
  fullName: __t.string().name("full_name"),
  email: __t.string(),
  get role() {
    return UserRole;
  },
  get authMethod() {
    return AuthMethod.name("auth_method");
  },
  accessKeyId: __t.option(__t.u64()).name("access_key_id"),
  joinedAt: __t.timestamp().name("joined_at"),
  lastLoginAt: __t.timestamp().name("last_login_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
