// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EntityStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  partyId: __t.u64().name("party_id"),
  pipelineId: __t.u64().name("pipeline_id"),
  get status() {
    return EntityStatus;
  },
  totalFils: __t.u64().name("total_fils"),
  poReference: __t.string().name("po_reference"),
  expectedDelivery: __t.option(__t.timestamp()).name("expected_delivery"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
