// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sku: __t.string(),
  name: __t.string(),
  category: __t.string(),
  supplierPartyId: __t.option(__t.u64()).name("supplier_party_id"),
  unitCostFils: __t.u64().name("unit_cost_fils"),
  unitPriceFils: __t.u64().name("unit_price_fils"),
  minMarkupBps: __t.u32().name("min_markup_bps"),
  hsCode: __t.string().name("hs_code"),
  description: __t.string(),
  isActive: __t.bool().name("is_active"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
