// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EntityStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  partyId: __t.u64().name("party_id"),
  orderId: __t.option(__t.u64()).name("order_id"),
  poNumber: __t.string().name("po_number"),
  deliveryTerms: __t.string().name("delivery_terms"),
  get status() {
    return EntityStatus;
  },
  totalFils: __t.u64().name("total_fils"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
