// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  MoneyEventKind,
} from "./types";

export default {
  partyId: __t.u64(),
  orderId: __t.option(__t.u64()),
  deliveryNoteId: __t.option(__t.u64()),
  get kind() {
    return MoneyEventKind;
  },
  subtotalFils: __t.u64(),
  reference: __t.string(),
  sourceDate: __t.option(__t.timestamp()),
  dueDate: __t.option(__t.timestamp()),
};
