// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  role: __t.string(),
  content: __t.string(),
  skillRequest: __t.option(__t.string()),
  approvalStatus: __t.option(__t.string()),
  transitionRequest: __t.option(__t.string()),
  pipelineContext: __t.option(__t.string()),
};
