// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddDeliveryNoteItemReducer from "../add_delivery_note_item_reducer";
import AddGrnItemReducer from "../add_grn_item_reducer";
import AddLineItemReducer from "../add_line_item_reducer";
import AdvanceDeliveryNoteReducer from "../advance_delivery_note_reducer";
import AdvanceGrnReducer from "../advance_grn_reducer";
import AdvancePipelineReducer from "../advance_pipeline_reducer";
import BootstrapAdminReducer from "../bootstrap_admin_reducer";
import ConvertPipelineToOrderReducer from "../convert_pipeline_to_order_reducer";
import CreateDeliveryNoteReducer from "../create_delivery_note_reducer";
import CreateGrnReducer from "../create_grn_reducer";
import DisputeBankTransactionReducer from "../dispute_bank_transaction_reducer";
import ImportBankTransactionReducer from "../import_bank_transaction_reducer";
import IssueAccessKeyReducer from "../issue_access_key_reducer";
import JoinMemberReducer from "../join_member_reducer";
import LogActivityReducer from "../log_activity_reducer";
import ManageOrderReducer from "../manage_order_reducer";
import ManagePurchaseOrderReducer from "../manage_purchase_order_reducer";
import MatchBankTransactionReducer from "../match_bank_transaction_reducer";
import NextDocNumberReducer from "../next_doc_number_reducer";
import ProposeAiActionReducer from "../propose_ai_action_reducer";
import RecordMoneyEventReducer from "../record_money_event_reducer";
import RedeemAccessKeyReducer from "../redeem_access_key_reducer";
import ResolveAiActionReducer from "../resolve_ai_action_reducer";
import RevokeAuthSessionReducer from "../revoke_auth_session_reducer";
import UnmatchBankTransactionReducer from "../unmatch_bank_transaction_reducer";
import UpsertAuthSessionReducer from "../upsert_auth_session_reducer";
import UpsertContactReducer from "../upsert_contact_reducer";
import UpsertPartyReducer from "../upsert_party_reducer";

export type AddDeliveryNoteItemParams = __Infer<typeof AddDeliveryNoteItemReducer>;
export type AddGrnItemParams = __Infer<typeof AddGrnItemReducer>;
export type AddLineItemParams = __Infer<typeof AddLineItemReducer>;
export type AdvanceDeliveryNoteParams = __Infer<typeof AdvanceDeliveryNoteReducer>;
export type AdvanceGrnParams = __Infer<typeof AdvanceGrnReducer>;
export type AdvancePipelineParams = __Infer<typeof AdvancePipelineReducer>;
export type BootstrapAdminParams = __Infer<typeof BootstrapAdminReducer>;
export type ConvertPipelineToOrderParams = __Infer<typeof ConvertPipelineToOrderReducer>;
export type CreateDeliveryNoteParams = __Infer<typeof CreateDeliveryNoteReducer>;
export type CreateGrnParams = __Infer<typeof CreateGrnReducer>;
export type DisputeBankTransactionParams = __Infer<typeof DisputeBankTransactionReducer>;
export type ImportBankTransactionParams = __Infer<typeof ImportBankTransactionReducer>;
export type IssueAccessKeyParams = __Infer<typeof IssueAccessKeyReducer>;
export type JoinMemberParams = __Infer<typeof JoinMemberReducer>;
export type LogActivityParams = __Infer<typeof LogActivityReducer>;
export type ManageOrderParams = __Infer<typeof ManageOrderReducer>;
export type ManagePurchaseOrderParams = __Infer<typeof ManagePurchaseOrderReducer>;
export type MatchBankTransactionParams = __Infer<typeof MatchBankTransactionReducer>;
export type NextDocNumberParams = __Infer<typeof NextDocNumberReducer>;
export type ProposeAiActionParams = __Infer<typeof ProposeAiActionReducer>;
export type RecordMoneyEventParams = __Infer<typeof RecordMoneyEventReducer>;
export type RedeemAccessKeyParams = __Infer<typeof RedeemAccessKeyReducer>;
export type ResolveAiActionParams = __Infer<typeof ResolveAiActionReducer>;
export type RevokeAuthSessionParams = __Infer<typeof RevokeAuthSessionReducer>;
export type UnmatchBankTransactionParams = __Infer<typeof UnmatchBankTransactionReducer>;
export type UpsertAuthSessionParams = __Infer<typeof UpsertAuthSessionReducer>;
export type UpsertContactParams = __Infer<typeof UpsertContactReducer>;
export type UpsertPartyParams = __Infer<typeof UpsertPartyReducer>;

