// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  UserRole,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  get role() {
    return UserRole;
  },
  assignedEmail: __t.string().name("assigned_email"),
  assignedName: __t.string().name("assigned_name"),
  notes: __t.string(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
  claimedBy: __t.option(__t.identity()).name("claimed_by"),
  claimedAt: __t.option(__t.timestamp()).name("claimed_at"),
  revokedAt: __t.option(__t.timestamp()).name("revoked_at"),
});
