// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  actorId: __t.identity().name("actor_id"),
  entityType: __t.string().name("entity_type"),
  entityId: __t.u64().name("entity_id"),
  action: __t.string(),
  detail: __t.string(),
  followUpDue: __t.option(__t.timestamp()).name("follow_up_due"),
  followUpDone: __t.bool().name("follow_up_done"),
  createdAt: __t.timestamp().name("created_at"),
});
