// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  EntityStatus,
} from "./types";

export default {
  id: __t.u64(),
  partyId: __t.u64(),
  title: __t.string(),
  get newStatus() {
    return EntityStatus;
  },
  estimatedValueFils: __t.u64(),
  winProbabilityBps: __t.u64(),
  competitorPresent: __t.bool(),
  oemPriceFils: __t.u64(),
  markupBps: __t.u64(),
  additionalCostsFils: __t.u64(),
  costingApproved: __t.bool(),
  offerSentAt: __t.option(__t.timestamp()),
  lossReason: __t.option(__t.string()),
  nextFollowUp: __t.option(__t.timestamp()),
};
