// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AiActionStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  requestorId: __t.identity().name("requestor_id"),
  skillName: __t.string().name("skill_name"),
  plan: __t.string(),
  get status() {
    return AiActionStatus;
  },
  approvedBy: __t.option(__t.identity()).name("approved_by"),
  result: __t.string(),
  errorMessage: __t.option(__t.string()).name("error_message"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
