// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AuthMethod,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  memberIdentity: __t.identity().name("member_identity"),
  sessionKey: __t.string().name("session_key"),
  sessionLabel: __t.string().name("session_label"),
  get authMethod() {
    return AuthMethod.name("auth_method");
  },
  issuedAt: __t.timestamp().name("issued_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
  revokedAt: __t.option(__t.timestamp()).name("revoked_at"),
  revokeReason: __t.option(__t.string()).name("revoke_reason"),
});
