// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  BankMatchStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  bankName: __t.string().name("bank_name"),
  transactionDate: __t.timestamp().name("transaction_date"),
  description: __t.string(),
  amountFils: __t.i64().name("amount_fils"),
  reference: __t.string(),
  matchedMoneyEventId: __t.option(__t.u64()).name("matched_money_event_id"),
  get matchStatus() {
    return BankMatchStatus.name("match_status");
  },
  importedAt: __t.timestamp().name("imported_at"),
  importedBy: __t.identity().name("imported_by"),
});
