// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DeliveryStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  orderId: __t.u64().name("order_id"),
  partyId: __t.u64().name("party_id"),
  dnNumber: __t.string().name("dn_number"),
  get status() {
    return DeliveryStatus;
  },
  deliveryDate: __t.timestamp().name("delivery_date"),
  deliveryAddress: __t.string().name("delivery_address"),
  driverName: __t.string().name("driver_name"),
  vehicleNumber: __t.string().name("vehicle_number"),
  receiverName: __t.string().name("receiver_name"),
  notes: __t.string(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
