// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  UserRole,
} from "./types";

export default {
  key: __t.string(),
  get role() {
    return UserRole;
  },
  assignedEmail: __t.string(),
  assignedName: __t.string(),
  notes: __t.string(),
  expiresAt: __t.option(__t.timestamp()),
};
