// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EntityStatus,
  MoneyEventKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  partyId: __t.u64().name("party_id"),
  orderId: __t.option(__t.u64()).name("order_id"),
  deliveryNoteId: __t.option(__t.u64()).name("delivery_note_id"),
  get kind() {
    return MoneyEventKind;
  },
  get status() {
    return EntityStatus;
  },
  subtotalFils: __t.u64().name("subtotal_fils"),
  vatFils: __t.u64().name("vat_fils"),
  totalFils: __t.u64().name("total_fils"),
  reference: __t.string(),
  dueDate: __t.option(__t.timestamp()).name("due_date"),
  paidAt: __t.option(__t.timestamp()).name("paid_at"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
