// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  CustomerGrade,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  code: __t.string(),
  category: __t.string(),
  isCustomer: __t.bool().name("is_customer"),
  isSupplier: __t.bool().name("is_supplier"),
  get grade() {
    return CustomerGrade;
  },
  creditLimitFils: __t.u64().name("credit_limit_fils"),
  isCreditBlocked: __t.bool().name("is_credit_blocked"),
  paymentTermsDays: __t.u64().name("payment_terms_days"),
  productTypes: __t.string().name("product_types"),
  annualGoalFils: __t.u64().name("annual_goal_fils"),
  city: __t.string(),
  country: __t.string(),
  phone: __t.string(),
  email: __t.string(),
  source: __t.string(),
  active2024: __t.bool().name("active_2024"),
  active2025: __t.bool().name("active_2025"),
  active2026: __t.bool().name("active_2026"),
  notes: __t.string(),
  bankIban: __t.string().name("bank_iban"),
  bankSwift: __t.string().name("bank_swift"),
  bankAccountName: __t.string().name("bank_account_name"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
