// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EntityStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  partyId: __t.u64().name("party_id"),
  ownerId: __t.identity().name("owner_id"),
  title: __t.string(),
  get status() {
    return EntityStatus;
  },
  estimatedValueFils: __t.u64().name("estimated_value_fils"),
  winProbabilityBps: __t.u64().name("win_probability_bps"),
  competitorPresent: __t.bool().name("competitor_present"),
  oemPriceFils: __t.u64().name("oem_price_fils"),
  markupBps: __t.u64().name("markup_bps"),
  additionalCostsFils: __t.u64().name("additional_costs_fils"),
  costingApproved: __t.bool().name("costing_approved"),
  costingApprovedBy: __t.option(__t.identity()).name("costing_approved_by"),
  offerTotalFils: __t.u64().name("offer_total_fils"),
  offerSentAt: __t.option(__t.timestamp()).name("offer_sent_at"),
  lossReason: __t.option(__t.string()).name("loss_reason"),
  nextFollowUp: __t.option(__t.timestamp()).name("next_follow_up"),
  revision: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
