// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccessKey = __t.object("AccessKey", {
  id: __t.u64(),
  key: __t.string(),
  get role() {
    return UserRole;
  },
  assignedEmail: __t.string(),
  assignedName: __t.string(),
  notes: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  expiresAt: __t.option(__t.timestamp()),
  claimedBy: __t.option(__t.identity()),
  claimedAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
});
export type AccessKey = __Infer<typeof AccessKey>;

export const ActivityLog = __t.object("ActivityLog", {
  id: __t.u64(),
  actorId: __t.identity(),
  entityType: __t.string(),
  entityId: __t.u64(),
  action: __t.string(),
  detail: __t.string(),
  followUpDue: __t.option(__t.timestamp()),
  followUpDone: __t.bool(),
  createdAt: __t.timestamp(),
});
export type ActivityLog = __Infer<typeof ActivityLog>;

export const AiAction = __t.object("AiAction", {
  id: __t.u64(),
  requestorId: __t.identity(),
  skillName: __t.string(),
  plan: __t.string(),
  get status() {
    return AiActionStatus;
  },
  approvedBy: __t.option(__t.identity()),
  result: __t.string(),
  errorMessage: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AiAction = __Infer<typeof AiAction>;

// The tagged union or sum type for the algebraic type `AiActionStatus`.
export const AiActionStatus = __t.enum("AiActionStatus", {
  Proposed: __t.unit(),
  Approved: __t.unit(),
  Executed: __t.unit(),
  Rejected: __t.unit(),
  Failed: __t.unit(),
});
export type AiActionStatus = __Infer<typeof AiActionStatus>;

export const AiMemory = __t.object("AiMemory", {
  id: __t.u64(),
  category: __t.string(),
  subject: __t.string(),
  content: __t.string(),
  confidence: __t.u32(),
  source: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  lastRelevantAt: __t.timestamp(),
  expiresAt: __t.option(__t.timestamp()),
});
export type AiMemory = __Infer<typeof AiMemory>;

// The tagged union or sum type for the algebraic type `AuthMethod`.
export const AuthMethod = __t.enum("AuthMethod", {
  Bootstrap: __t.unit(),
  InviteKey: __t.unit(),
});
export type AuthMethod = __Infer<typeof AuthMethod>;

export const AuthSession = __t.object("AuthSession", {
  id: __t.u64(),
  memberIdentity: __t.identity(),
  sessionKey: __t.string(),
  sessionLabel: __t.string(),
  get authMethod() {
    return AuthMethod;
  },
  issuedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  revokedAt: __t.option(__t.timestamp()),
  revokeReason: __t.option(__t.string()),
});
export type AuthSession = __Infer<typeof AuthSession>;

// The tagged union or sum type for the algebraic type `BankMatchStatus`.
export const BankMatchStatus = __t.enum("BankMatchStatus", {
  Unmatched: __t.unit(),
  Matched: __t.unit(),
  Disputed: __t.unit(),
});
export type BankMatchStatus = __Infer<typeof BankMatchStatus>;

export const BankTransaction = __t.object("BankTransaction", {
  id: __t.u64(),
  bankName: __t.string(),
  transactionDate: __t.timestamp(),
  description: __t.string(),
  amountFils: __t.i64(),
  reference: __t.string(),
  matchedMoneyEventId: __t.option(__t.u64()),
  get matchStatus() {
    return BankMatchStatus;
  },
  importedAt: __t.timestamp(),
  importedBy: __t.identity(),
});
export type BankTransaction = __Infer<typeof BankTransaction>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  memberId: __t.identity(),
  role: __t.string(),
  content: __t.string(),
  skillRequest: __t.option(__t.string()),
  approvalStatus: __t.option(__t.string()),
  transitionRequest: __t.option(__t.string()),
  pipelineContext: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Contact = __t.object("Contact", {
  id: __t.u64(),
  partyId: __t.u64(),
  name: __t.string(),
  designation: __t.string(),
  phone: __t.string(),
  email: __t.string(),
  isWhatsApp: __t.bool(),
});
export type Contact = __Infer<typeof Contact>;

// The tagged union or sum type for the algebraic type `CustomerGrade`.
export const CustomerGrade = __t.enum("CustomerGrade", {
  A: __t.unit(),
  B: __t.unit(),
  C: __t.unit(),
  D: __t.unit(),
});
export type CustomerGrade = __Infer<typeof CustomerGrade>;

export const DeliveryNote = __t.object("DeliveryNote", {
  id: __t.u64(),
  orderId: __t.u64(),
  partyId: __t.u64(),
  dnNumber: __t.string(),
  get status() {
    return DeliveryStatus;
  },
  deliveryDate: __t.timestamp(),
  deliveryAddress: __t.string(),
  driverName: __t.string(),
  vehicleNumber: __t.string(),
  receiverName: __t.string(),
  notes: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DeliveryNote = __Infer<typeof DeliveryNote>;

export const DeliveryNoteItem = __t.object("DeliveryNoteItem", {
  id: __t.u64(),
  deliveryNoteId: __t.u64(),
  lineItemId: __t.u64(),
  quantityDelivered: __t.u64(),
  notes: __t.string(),
});
export type DeliveryNoteItem = __Infer<typeof DeliveryNoteItem>;

// The tagged union or sum type for the algebraic type `DeliveryStatus`.
export const DeliveryStatus = __t.enum("DeliveryStatus", {
  Draft: __t.unit(),
  Dispatched: __t.unit(),
  Delivered: __t.unit(),
  Returned: __t.unit(),
});
export type DeliveryStatus = __Infer<typeof DeliveryStatus>;

export const DocSequence = __t.object("DocSequence", {
  id: __t.u64(),
  docType: __t.string(),
  year: __t.u32(),
  lastNumber: __t.u32(),
});
export type DocSequence = __Infer<typeof DocSequence>;

// The tagged union or sum type for the algebraic type `EntityStatus`.
export const EntityStatus = __t.enum("EntityStatus", {
  Draft: __t.unit(),
  Active: __t.unit(),
  InProgress: __t.unit(),
  Terminal: __t.unit(),
  Cancelled: __t.unit(),
});
export type EntityStatus = __Infer<typeof EntityStatus>;

export const FxRate = __t.object("FxRate", {
  id: __t.u64(),
  fromCurrency: __t.string(),
  toCurrency: __t.string(),
  rate: __t.u64(),
  rateScale: __t.u32(),
  effectiveDate: __t.timestamp(),
  source: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type FxRate = __Infer<typeof FxRate>;

export const GoodsReceivedNote = __t.object("GoodsReceivedNote", {
  id: __t.u64(),
  purchaseOrderId: __t.u64(),
  grnNumber: __t.string(),
  get status() {
    return GrnStatus;
  },
  receivedDate: __t.timestamp(),
  receivedBy: __t.identity(),
  inspectionNotes: __t.string(),
  createdAt: __t.timestamp(),
});
export type GoodsReceivedNote = __Infer<typeof GoodsReceivedNote>;

export const GrnItem = __t.object("GrnItem", {
  id: __t.u64(),
  grnId: __t.u64(),
  lineItemId: __t.u64(),
  quantityReceived: __t.u64(),
  quantityAccepted: __t.u64(),
  notes: __t.string(),
});
export type GrnItem = __Infer<typeof GrnItem>;

// The tagged union or sum type for the algebraic type `GrnStatus`.
export const GrnStatus = __t.enum("GrnStatus", {
  Draft: __t.unit(),
  Inspecting: __t.unit(),
  Accepted: __t.unit(),
  Rejected: __t.unit(),
});
export type GrnStatus = __Infer<typeof GrnStatus>;

export const LineItem = __t.object("LineItem", {
  id: __t.u64(),
  parentType: __t.string(),
  parentId: __t.u64(),
  description: __t.string(),
  quantity: __t.u64(),
  unitPriceFils: __t.u64(),
  totalPriceFils: __t.u64(),
  fobCostFils: __t.u64(),
  freightCostFils: __t.u64(),
  customsCostFils: __t.u64(),
  insuranceCostFils: __t.u64(),
  handlingCostFils: __t.u64(),
  financeCostFils: __t.u64(),
  marginBps: __t.u32(),
  costPerUnitFils: __t.u64(),
});
export type LineItem = __Infer<typeof LineItem>;

export const Member = __t.object("Member", {
  identity: __t.identity(),
  nickname: __t.string(),
  fullName: __t.string(),
  email: __t.string(),
  get role() {
    return UserRole;
  },
  get authMethod() {
    return AuthMethod;
  },
  accessKeyId: __t.option(__t.u64()),
  joinedAt: __t.timestamp(),
  lastLoginAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Member = __Infer<typeof Member>;

export const MoneyEvent = __t.object("MoneyEvent", {
  id: __t.u64(),
  partyId: __t.u64(),
  orderId: __t.option(__t.u64()),
  deliveryNoteId: __t.option(__t.u64()),
  get kind() {
    return MoneyEventKind;
  },
  get status() {
    return EntityStatus;
  },
  subtotalFils: __t.u64(),
  vatFils: __t.u64(),
  totalFils: __t.u64(),
  reference: __t.string(),
  sourceDate: __t.option(__t.timestamp()),
  dueDate: __t.option(__t.timestamp()),
  paidAt: __t.option(__t.timestamp()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MoneyEvent = __Infer<typeof MoneyEvent>;

// The tagged union or sum type for the algebraic type `MoneyEventKind`.
export const MoneyEventKind = __t.enum("MoneyEventKind", {
  CustomerInvoice: __t.unit(),
  CustomerPayment: __t.unit(),
  SupplierInvoice: __t.unit(),
  SupplierPayment: __t.unit(),
});
export type MoneyEventKind = __Infer<typeof MoneyEventKind>;

export const Order = __t.object("Order", {
  id: __t.u64(),
  partyId: __t.u64(),
  pipelineId: __t.option(__t.u64()),
  get status() {
    return EntityStatus;
  },
  totalFils: __t.u64(),
  poReference: __t.string(),
  source: __t.string(),
  expectedDelivery: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Order = __Infer<typeof Order>;

export const Party = __t.object("Party", {
  id: __t.u64(),
  name: __t.string(),
  code: __t.string(),
  category: __t.string(),
  isCustomer: __t.bool(),
  isSupplier: __t.bool(),
  get grade() {
    return CustomerGrade;
  },
  creditLimitFils: __t.u64(),
  isCreditBlocked: __t.bool(),
  paymentTermsDays: __t.u64(),
  productTypes: __t.string(),
  annualGoalFils: __t.u64(),
  city: __t.string(),
  country: __t.string(),
  phone: __t.string(),
  email: __t.string(),
  source: __t.string(),
  active2024: __t.bool(),
  active2025: __t.bool(),
  active2026: __t.bool(),
  notes: __t.string(),
  bankIban: __t.string(),
  bankSwift: __t.string(),
  bankAccountName: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Party = __Infer<typeof Party>;

export const Pipeline = __t.object("Pipeline", {
  id: __t.u64(),
  partyId: __t.u64(),
  ownerId: __t.identity(),
  title: __t.string(),
  legacyYear: __t.option(__t.u32()),
  opportunityNumber: __t.string(),
  folderNumber: __t.string(),
  folderName: __t.string(),
  sfdcTitle: __t.string(),
  comment: __t.string(),
  ehReference: __t.string(),
  paymentTerms: __t.string(),
  ownerName: __t.string(),
  source: __t.string(),
  sourceNotes: __t.string(),
  deliverySummary: __t.string(),
  get status() {
    return EntityStatus;
  },
  estimatedValueFils: __t.u64(),
  winProbabilityBps: __t.u64(),
  competitorPresent: __t.bool(),
  oemPriceFils: __t.u64(),
  markupBps: __t.u64(),
  additionalCostsFils: __t.u64(),
  costingApproved: __t.bool(),
  costingApprovedBy: __t.option(__t.identity()),
  offerTotalFils: __t.u64(),
  offerSentAt: __t.option(__t.timestamp()),
  lossReason: __t.option(__t.string()),
  nextFollowUp: __t.option(__t.timestamp()),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Pipeline = __Infer<typeof Pipeline>;

export const Product = __t.object("Product", {
  id: __t.u64(),
  sku: __t.string(),
  name: __t.string(),
  category: __t.string(),
  supplierPartyId: __t.option(__t.u64()),
  unitCostFils: __t.u64(),
  unitPriceFils: __t.u64(),
  minMarkupBps: __t.u32(),
  hsCode: __t.string(),
  description: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Product = __Infer<typeof Product>;

export const PurchaseOrder = __t.object("PurchaseOrder", {
  id: __t.u64(),
  partyId: __t.u64(),
  orderId: __t.option(__t.u64()),
  poNumber: __t.string(),
  deliveryTerms: __t.string(),
  source: __t.string(),
  get status() {
    return EntityStatus;
  },
  totalFils: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PurchaseOrder = __Infer<typeof PurchaseOrder>;

export const StockEntry = __t.object("StockEntry", {
  id: __t.u64(),
  productId: __t.u64(),
  entryType: __t.string(),
  quantity: __t.i64(),
  referencePo: __t.string(),
  referenceGrn: __t.string(),
  notes: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type StockEntry = __Infer<typeof StockEntry>;

// The tagged union or sum type for the algebraic type `UserRole`.
export const UserRole = __t.enum("UserRole", {
  Admin: __t.unit(),
  Manager: __t.unit(),
  Sales: __t.unit(),
  Operations: __t.unit(),
  Accountant: __t.unit(),
});
export type UserRole = __Infer<typeof UserRole>;

