// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.u64(),
  sku: __t.string(),
  name: __t.string(),
  category: __t.string(),
  supplierPartyId: __t.option(__t.u64()),
  unitCostFils: __t.u64(),
  unitPriceFils: __t.u64(),
  minMarkupBps: __t.u32(),
  hsCode: __t.string(),
  description: __t.string(),
  isActive: __t.bool(),
};
